version: '3.3'
services:
  spring-web:
    build:
      context: ./
      dockerfile: ./spring-web/Dockerfile
    ports:
      - "8080:8080"
  java-cross-section:
    build:
      context: ./
      dockerfile: ./java-cross-section/Dockerfile
    ports:
      - "8082:8082"
  go-heatmap:
    build: go-heatmap
    ports:
      - "8081:8081"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
